# Generated by Django 4.2.4 on 2023-08-26 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AddField(
            model_name='habit',
            name='action',
            field=models.CharField(default='pass', max_length=150, verbose_name='действие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AddField(
            model_name='habit',
            name='execution_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время на выполнение'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=True, verbose_name='признак полезной привычки'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='признак публичности'),
        ),
        migrations.AddField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(default=1, verbose_name='периодичность в днях'),
        ),
        migrations.AddField(
            model_name='habit',
            name='place',
            field=models.CharField(default='pass', max_length=150, verbose_name='место'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.habit', verbose_name='связанная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='время'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='title',
            field=models.CharField(default='pass', max_length=150, verbose_name='название'),
            preserve_default=False,
        ),
    ]
